name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Build container image
      run: docker build -t ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/digital-ocean-wordpress:$(echo $GITHUB_SHA | head -c7) .

    - name: Authenticate to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/digital-ocean-wordpress:$(echo $GITHUB_SHA | head -c7)
